#!/bin/bash

# Ellenőrizzük, hogy egy paramétert kaptunk-e
if [[ $# -ne 1 ]]; then
    echo "Hiba: Adj meg egy pozitív egész számot!" >&2
    exit 1
fi

# Ellenőrizzük, hogy a paraméter pozitív egész szám-e
szam=$1
if ! [[ $szam =~ ^[0-9]+$ ]]; then
    echo "Hiba: Csak pozitív egész számot adhatsz meg!" >&2
    exit 1
fi

# Visszaszámolás
for ((i=szam; i>0; i--)); do
    echo "$i"
done
