#!/bin/bash
file=$1
while IFS= read -r line; do
            # Ellenőrizzük, hogy a szám páros-e
                if [[ $((line % 2)) -eq 0 ]]; then
                        echo "$line"
                            fi
                            done < "$file"
